### ISSUE TITLE
Solves bazel issues on NixOS

### ISSUE THREAD

**Issue by archite** [nix-community/nix-ld-rs#1]
I just started testing this but it so far resolves issues using deterministic Python/Go toolchains that `nix-ld` would break on.

Thanks for the effort and keep it up! This has solved loads of problems for me.

**Comment by fd** [comment]
Just wanted to chime in. This is truly amazing! VSCode is no longer a pain to run over ssh on a NixOS remote.

**Comment by Mic92** [comment]
I will make a release and add it to nixpkgs soonish.
