### ISSUE TITLE
Configuration fragment for using?

### ISSUE THREAD

**Issue by pwaller** [nix-community/nix-ld-rs#3]
nix-ld-rs looks interesting! Glad to see it in nix-community. Is it ready for use or at least experimentation?

I'm sure it's obvious in hindsight, but is there a configuration fragment I can paste into my configuration.nix to make use of nix-ld-rs? This is something I can likely solve myself but I'm interested in seeing it documented at the top of the readme for other people as well.

Right now I imagine I might need to import nix-ld-rs as a flake, but is there also a plan to get this integrated into nixpkgs and nixos?

**Comment by Cu3PO42** [comment]
You can use it via the existing NixOS module for `nix-ld`. The following snippet works:
```
programs.nix-ld.enable = true;
programs.nix-ld.package = nix-ld-rs;
```
where you have made the `nix-ld-rs` package available in an eponymous variable. One option to achieve that in a config using Flakes would be to add this repo as an input, make `inputs` available to your configuration via `specialArgs` and then refer to `inputs.nix-ld-rs.packages.${pkgs.system}.default`.
