### ISSUE TITLE
newb question

### ISSUE THREAD

**Issue by Bee-Mar** [nix-community/nix-ld-rs#8]
Hello,

Sorry, I am relatively new to Nix & NixOS, and would like to install this package, but don't know how. Is it possible to provide some information? My configuration is currently flake-based.

**Comment by cgeopapa** [comment]
I wasn't sure how as well, but I found [this](https://github.com/Mic92/dotfiles/blob/main/nixos/modules/nix-ld.nix) nix file from the creator of nix-ld. Check out the flake.nix file as well.

**Comment by Bee-Mar** [comment]
@cgeopapa aaahh this is way more clear, thank you!
